#!/bin/bash
# apt-source-install v1.0.0 created by Nathaniel Greenwell (NTVMB)
# designed for Debtoo GNU/Linux or other Debian-based distros
VERSION=1.0.0

# Warn if running as root
if [ $EUID -eq 0 ]
	then echo "Avoid running this script as root/sudo."
fi

# Check for locks created by apt
find /var/lib/dpkg/lock-frontend > /dev/null
if [ $? -eq 0 ]
	then echo "Error: Please close all other package managers before running this script."
	echo "If a package manager closed unexpectedly, delete the file '/var/lib/dpkg/lock-frontend'"
	exit 1
fi

# Get build dependencies if necessary
echo "Getting build dependencies if necessary..."
sudo apt -y build-dep $@
if [ $? -ne 0 ]
	then echo "Error: Command failed to execute."
	exit 126
fi

# Get source package(s), build, and install them
echo "Getting and building source package(s)..."
apt source -b $@
if [ $? -ne 0 ]
	then echo "Error: Command failed to execute."
	exit 126
fi
if [ ! -d ./debs ]
	then if [ -e ./debs ]
		then rm -f ./debs
	fi
	mkdir ./debs
fi
mv *.deb ./debs
echo "Installing package(s)..."
sudo dpkg -iER ./debs
if [ $? -ne 0 ]
	then echo "Error: Failed to install package(s)"
	exit 1
fi

# Clean up
echo "Cleaning up..."
rm -fv ./debs/*
echo "Success"
